services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention=12h'
      - '--storage.tsdb.wal-compression'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - prometheus

  gatling-at-once:
    image: denvazh/gatling:latest
    container_name: gatling-at-once
    volumes:
      - ./gatling/simulations:/opt/gatling/user-files/simulations
      - ./gatling/results:/opt/gatling/results
    depends_on:
      - echo-server
      - gin-server
    entrypoint: ["/bin/sh", "-c", "gatling.sh -s ServerAtOnceLoadSimulation"]

  gatling-per-second:
    image: denvazh/gatling:latest
    container_name: gatling-per-second
    volumes:
      - ./gatling/simulations:/opt/gatling/user-files/simulations
      - ./gatling/results:/opt/gatling/results
    depends_on:
      gatling-at-once:
        condition: service_completed_successfully
    entrypoint: ["/bin/sh", "-c", "gatling.sh -s ServerPerSecondLoadSimulation"]

  echo-server:
    image: go_env:latest
    container_name: echo-server
    ports:
      - "8081:8081"
    depends_on:
      - prometheus
    environment:
      GOMAXPROCS: 1
    entrypoint: ["/bin/sh", "-c", "go run prometheus/echo/core.go"]

  gin-server:
    image: go_env:latest
    container_name: gin-server
    ports:
      - "8082:8081"
    depends_on:
      - prometheus
    environment:
      GOMAXPROCS: 1
    entrypoint: ["/bin/sh", "-c", "go run prometheus/gin/core.go"]