logger:
  level: 'info'
  file: 'out.log'

auth:
  signingKey: "racket_shop"
  accessTokenTTL: 12h

http:
  port: 8082

database:
  postgres:
    host: 'localhost'
    port: 5432
    user: 'postgres'
    password: 'admin'
    database: 'tests'

2fa:
  email: ""
  password: ""
  port: 587